name: "Merge Dependabot PRs"

on:
  workflow_run:
    types:
      - "completed"
    workflows:
      - "Continuous Integration"

jobs:
  merge-me:
    name: "Merge me!"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Auto-merge"
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: "ridedott/merge-me-action@v2.10.64"
        with:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}